import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import Headertop from "../components/HeaderTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="bg-white dark:bg-c89bec min-h-screen">
        <Headertop />
        {children}
      </body>
    </html>
  );
}
