import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import Headertop from "../components/HeaderTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Baloo+Bhaina+2:wght@400;500;600;700;800&display=swap" rel="stylesheet" />
      </head>
      <body className="bg-white dark:bg-c89bec min-h-screen">
        <Headertop />
        {children}
      </body>
    </html>
  );
}
