"use client";

import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ko" | "en" | "ja" | "zh" | "tr";

export const LANGUAGES: { code: Language; name: string; flag: string }[] = [
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "zh", name: "中文", flag: "🇨🇳" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 번역 데이터
const translations: Record<Language, Record<string, string>> = {
  ko: {
    // Navigation
    "nav.play": "플레이",
    "nav.market": "마켓",
    "nav.swap": "스왑",
    "nav.earn": "수익",
    "nav.voting": "투표",
    "nav.more": "더보기",

    // Main Page
    "main.defineYourLegacy": "당신의 전설을 만드세요",
    "main.theEra": "시대",
    "main.genre": "장르",
    "main.chooseYourPath": "당신의 길을 선택하세요",

    // Voting Page
    "voting.title": "투표",
    "voting.subtitle": "세계의 운명을 투표로 결정하세요.",
    "voting.createVoting": "투표 생성",
    "voting.proposal": "제안",
    "voting.ongoing": "진행중",
    "voting.ended": "종료됨",
    "voting.approve": "승인",
    "voting.reject": "거절",
    "voting.pending": "검토중",
    "voting.treasury": "트레저리",
    "voting.totalProposals": "총 제안",
    "voting.approved": "승인",
    "voting.rejected": "거절",
    "voting.noPermission": "이 게임의 운영자만 투표를 생성할 수 있습니다",
    "voting.storyView": "스토리 뷰",
    "voting.daoView": "DAO 뷰",
    "voting.mainstream": "메인스트림",
    "voting.stream": "스트림",
    "voting.vtdnBalance": "VTDN 잔액",
    "voting.proposalCount": "제안",
    "voting.approvedCount": "승인",
    "voting.rejectedCount": "거절",
    "voting.votingPower": "투표력",
    "voting.noVotingPower": "투표력이 없습니다",
    "voting.titleColumn": "제목",
    "voting.stage": "스테이지",
    "voting.status": "상태",
    "voting.votes": "투표",
    "voting.remaining": "남은 시간",
    "voting.noOngoing": "진행 중인 투표가 없습니다",
    "voting.noEnded": "종료된 투표가 없습니다",
    "voting.upvote": "추천",
    "voting.downvote": "비추천",
    "voting.upvoteReaction": "추천했습니다",
    "voting.downvoteReaction": "비추천했습니다",
    "voting.proposer": "제안자",
    "voting.game": "게임",
    "voting.noProposals": "제안이 없습니다",
    "voting.noProposalsStatus": "제안이 없습니다",
    "voting.approvalDuration": "투표 기간 설정",
    "voting.preset": "프리셋",
    "voting.custom": "직접 입력",
    "voting.days": "일",
    "voting.hours": "시간",
    "voting.minutes": "분",
    "voting.participation": "참여",
    "voting.onchain": "온체인",
    "voting.voted": "투표함",
    "voting.decided": "결정됨",
    "voting.revoteNeeded": "재투표 필요",
    "voting.noUserGames": "유저 생성 게임 없음",
    "voting.proposalDate": "제안일",
    "voting.statusAdmin": "상태 / 관리",
    "voting.upvoteDownvote": "추천/비추천",
    "voting.proposalContent": "제안 내용",
    "voting.loadFailed": "투표 목록을 불러오는데 실패했습니다",
    "voting.approveConfirm": "제안 승인",
    "voting.startVoting": "투표 시작",
    "voting.voteDurationSet": "투표 기간을 설정해주세요",
    "voting.proposalApprovedVoting": "제안이 승인되어 투표가 진행됩니다!",
    "voting.proposalApproved": "제안이 승인되었습니다",
    "voting.proposalRejected": "제안이 거절되었습니다",
    "voting.adminRequired": "관리자 권한이 필요합니다",
    "voting.connectWallet": "지갑을 연결해주세요",
    "voting.voteFailed": "투표에 실패했습니다",
    "voting.voteError": "투표 중 오류가 발생했습니다",
    "voting.processingFailed": "처리에 실패했습니다",
    "voting.voteResultApplied": "투표 결과가 반영되었습니다!",
    "voting.votingGuide": "투표 안내",
    "voting.guide1": "투표는 게임 플레이 중 해당 선택지에서만 가능합니다",
    "voting.guide2": "온체인 투표: 블록체인에 영구 기록되며 투명하게 검증 가능합니다",
    "voting.guide3": "이 페이지에서는 현재 진행 중인 투표 현황을 확인할 수 있습니다",
    "voting.guide4": "지갑 주소당 1회 투표 가능합니다",
    "voting.guide5": "투표 종료 후 과반수를 득표한 선택지만 게임에서 선택할 수 있습니다",
    "voting.guide6": "과반수를 득표하지 못한 경우 재투표가 필요합니다",
    "voting.daoContract": "VeryDAOIntegrated 컨트랙트",
    "voting.votingPeriod": "투표 기간",
    "voting.threeDays": "3일",
    "voting.proposalRequirement": "프로포절 생성 조건",
    "voting.minVery": "최소 1 VERY 보유",
    "voting.setting": "설정",
    "voting.selectDuration": "투표 기간 선택",
    "voting.customDuration": "투표 기간 직접 설정",
    // Create Voting Modal
    "voting.createModal.title": "투표 생성",
    "voting.createModal.titleLabel": "제목 *",
    "voting.createModal.titlePlaceholder": "투표 제목을 입력하세요",
    "voting.createModal.descLabel": "설명",
    "voting.createModal.descPlaceholder": "투표 설명을 입력하세요 (선택)",
    "voting.createModal.stageLabel": "스테이지 *",
    "voting.createModal.stagePlaceholder": "스테이지를 선택하세요",
    "voting.createModal.choicesLabel": "선택지 * (최소 2개)",
    "voting.createModal.noChoices": "이 스테이지에 선택지가 없습니다",
    "voting.createModal.duration": "투표 기간",
    "voting.createModal.hour": "시간",
    "voting.createModal.day": "일",
    "voting.createModal.creating": "생성 중...",
    "voting.createModal.enterTitle": "제목을 입력하세요",
    "voting.createModal.selectStage": "스테이지를 선택하세요",
    "voting.createModal.minChoices": "최소 2개의 선택지를 선택하세요",
    "voting.createModal.created": "투표가 생성되었습니다!",
    "voting.createModal.failed": "투표 생성에 실패했습니다",
    // Proposal Modal
    "voting.proposalModal.title": "제안하기",
    "voting.proposalModal.newProposal": "새 제안",
    "voting.proposalModal.proposalList": "제안 목록",
    "voting.proposalModal.titleLabel": "제안 제목 *",
    "voting.proposalModal.titlePlaceholder": "어떤 투표를 제안하시나요?",
    "voting.proposalModal.descLabel": "상세 설명",
    "voting.proposalModal.descPlaceholder": "제안에 대한 자세한 설명을 입력하세요 (선택)",
    "voting.proposalModal.stageLabel": "관련 스테이지 (선택)",
    "voting.proposalModal.stagePlaceholder": "스테이지를 선택하세요 (선택사항)",
    "voting.proposalModal.costInfo": "제안 등록 시",
    "voting.proposalModal.costAmount": "1 VERY",
    "voting.proposalModal.costSuffix": "가 소모됩니다.",
    "voting.proposalModal.reviewInfo": "제안은 관리자/운영자가 검토 후 투표로 전환됩니다.",
    "voting.proposalModal.submit": "1 VERY로 제안하기",
    "voting.proposalModal.submitButton": "1 VERY로 제안하기",
    "voting.proposalModal.submitting": "제안 등록 중...",
    "voting.proposalModal.registering": "제안 등록 중...",
    "voting.proposalModal.txPending": "트랜잭션 처리 중...",
    "voting.proposalModal.txProcessing": "트랜잭션 처리 중...",
    "voting.proposalModal.noProposals": "아직 제안이 없습니다. 첫 번째 제안을 해보세요!",
    "voting.proposalModal.relatedStage": "관련 스테이지",
    "voting.proposalModal.enterTitle": "제목을 입력하세요",
    "voting.proposalModal.registered": "제안이 등록되었습니다!",
    "voting.proposalModal.registerFailed": "제안 등록에 실패했습니다",
    "voting.proposalModal.txFailed": "트랜잭션이 실패했습니다",
    "voting.proposalModal.txError": "트랜잭션 중 오류가 발생했습니다",
    "voting.proposalModal.connectWallet": "지갑 연결을 해주세요.",
    "voting.proposalModal.walletRejected": "지갑 연결을 거부했습니다.",
    "voting.proposalModal.txApprove": "트랜잭션을 승인해주세요...",
    "voting.proposalModal.noMetaMask": "MetaMask가 감지되지 않았습니다.",
    "voting.proposalModal.veryMainnetFailed": "VERY 메인넷 추가에 실패했습니다.",
    "voting.proposalModal.switchVery": "VERY 메인넷으로 전환해주세요.",
    "voting.proposalModal.pendingStatus": "검토중",
    "voting.proposalModal.approvedStatus": "승인됨",
    "voting.proposalModal.rejectedStatus": "거절됨",
    "voting.proposalModal.convertedStatus": "투표로 전환됨",

    // Play Page
    "play.mainstream": "Mainstream",
    "play.mainStream": "Main Stream",
    "play.stream": "Stream",
    "play.createStream": "스트림 생성",
    "play.create": "+ 생성",
    "play.players": "플레이어",
    "play.era": "시대",
    "play.genre": "장르",
    "play.plan": "요금제",
    "play.schedule": "일정",
    "play.title": "제목",
    "play.all": "전체",
    "play.playDescription": "다양한 스트림을 플레이하거나 새로운 스트림을 만들어 보세요.",
    "play.play": "플레이",
    "play.free": "무료",
    "play.paid": "유료",
    "play.unlimited": "무제한",
    "play.limited": "제한",
    // Create Stream Modal
    "play.createModal.title": "스트림 생성",
    "play.createModal.titleLabel": "제목",
    "play.createModal.titlePlaceholder": "스트림 제목을 입력하세요",
    "play.createModal.eraLabel": "시대",
    "play.createModal.eraPlaceholder": "시대를 선택하세요",
    "play.createModal.customEraPlaceholder": "직접 입력",
    "play.createModal.genreLabel": "장르",
    "play.createModal.genrePlaceholder": "장르를 선택하세요",
    "play.createModal.customGenrePlaceholder": "직접 입력",
    "play.createModal.playersLabel": "플레이어",
    "play.createModal.playersPlaceholder": "플레이어 수를 입력하세요",
    "play.createModal.planLabel": "요금제",
    "play.createModal.planFeePlaceholder": "요금을 입력하세요",
    "play.createModal.scheduleLabel": "일정",
    "play.createModal.monthly": "매월",
    "play.createModal.weekly": "매주",
    "play.createModal.daily": "매일",
    "play.createModal.custom": "직접 입력",
    "play.createModal.customSchedulePlaceholder": "일정을 입력하세요",
    "play.createModal.imageLabel": "스트림 이미지",
    "play.createModal.createSuccess": "스트림이 성공적으로 생성되었습니다!",
    "play.createModal.createFailed": "스트림 생성에 실패했습니다",
    "play.createModal.uploadImage": "스트림 이미지를 업로드해주세요",
    "play.createModal.uploadFailed": "이미지 업로드에 실패했습니다",
    "play.createModal.unexpectedError": "예기치 않은 오류가 발생했습니다",
    "play.createModal.others": "기타",
    "play.createModal.week": "주차",
    // Game Filter
    "play.filter.era": "시대",
    "play.filter.genre": "장르",
    "play.filter.players": "플레이어",
    "play.filter.free": "무료",
    "play.filter.all": "전체",

    // Earn Page
    "earn.adsVery": "AdsVery",
    "earn.walletNotConnected": "지갑이 연결되지 않았습니다.",
    "earn.alreadyClaimed": "오늘 이미 받았습니다. 내일 다시 오세요!",
    "earn.pleaseWait": "잠시 후에 다시 클릭해주세요.",
    "earn.claimed": "받기 완료!",
    "earn.noRewards": "받을 보상이 없습니다!",
    "earn.claimDone": "VTDN 받기 완료",
    "earn.metamaskNotInstalled": "Metamask가 설치되지 않았습니다.",

    // Market Page
    "market.title": "NFT 마켓플레이스",
    "market.connectWallet": "지갑을 연결하여 NFT를 탐색하세요",
    "market.marketplace": "마켓플레이스",
    "market.myCollection": "내 컬렉션",
    "market.collections": "컬렉션",
    "market.items": "개 아이템",
    "market.availableForPurchase": "구매 가능",
    "market.inYourWallet": "내 지갑에 있음",
    "market.search": "이름 또는 토큰 ID로 NFT 검색...",
    "market.recent": "최신순",
    "market.low": "낮은 가격",
    "market.high": "높은 가격",
    "market.highestPrice": "최고가",
    "market.lowestPrice": "최저가",
    "market.connectedWith": "연결된 지갑",
    "market.walletAddress": "지갑 주소",
    "market.disconnect": "연결 해제",
    "market.buy": "구매",
    "market.sell": "판매",
    "market.list": "등록",
    "market.cancel": "취소",
    "market.price": "가격",
    "market.seller": "판매자",
    "market.quantity": "수량",
    "market.total": "총액",
    "market.category.all": "전체",
    "market.category.weapon": "무기",
    "market.category.shoes": "신발",
    "market.category.gloves": "장갑",
    "market.category.pants": "바지",
    "market.category.top": "상의",
    "market.category.cloak": "망토",
    "market.category.helmet": "투구",
    "market.category.accessory": "장신구",
    "market.category.title": "칭호",
    "market.category.skill": "스킬",
    "market.listModal.title": "NFT 판매 등록",
    "market.listModal.priceLabel": "가격 (VERY)",
    "market.listModal.pricePlaceholder": "판매 가격을 입력하세요",
    "market.listModal.quantityLabel": "수량",
    "market.listModal.submit": "등록하기",
    "market.listModal.submitting": "등록 중...",
    "market.sellerModal.title": "판매자 선택",
    "market.sellerModal.selectSeller": "구매할 판매자를 선택하세요",
    "market.sellerModal.quantity": "수량",
    "market.sellerModal.available": "사용 가능",
    "market.sellerModal.buy": "구매",
    "market.history.title": "거래 내역",
    "market.history.noHistory": "거래 내역이 없습니다",
    "market.history.bought": "구매",
    "market.history.sold": "판매",
    "market.history.listed": "등록",
    "market.history.cancelled": "취소",

    // Common
    "common.connect": "연결",
    "common.disconnect": "연결 해제",
    "common.loading": "로딩 중...",
    "common.confirm": "확인",
    "common.cancel": "취소",
    "common.save": "저장",
    "common.delete": "삭제",
    "common.edit": "수정",
    "common.search": "검색",
    "common.filter": "필터",
    "common.all": "전체",
  },
  en: {
    // Navigation
    "nav.play": "Play",
    "nav.market": "Market",
    "nav.swap": "Swap",
    "nav.earn": "Earn",
    "nav.voting": "Voting",
    "nav.more": "More",

    // Main Page
    "main.defineYourLegacy": "DEFINE YOUR LEGACY",
    "main.theEra": "THE ERA",
    "main.genre": "GENRE",
    "main.chooseYourPath": "CHOOSE YOUR PATH",

    // Voting Page
    "voting.title": "Voting",
    "voting.subtitle": "Decide the world's fate through voting.",
    "voting.createVoting": "Create Vote",
    "voting.proposal": "Proposal",
    "voting.ongoing": "Ongoing",
    "voting.ended": "Ended",
    "voting.approve": "Approve",
    "voting.reject": "Reject",
    "voting.pending": "Pending",
    "voting.treasury": "Treasury",
    "voting.totalProposals": "Total Proposals",
    "voting.approved": "Approved",
    "voting.rejected": "Rejected",
    "voting.noPermission": "Only game operators can create votes",
    "voting.storyView": "Story View",
    "voting.daoView": "DAO View",
    "voting.mainstream": "Mainstream",
    "voting.stream": "Stream",
    "voting.vtdnBalance": "VTDN Balance",
    "voting.proposalCount": "Proposals",
    "voting.approvedCount": "Approved",
    "voting.rejectedCount": "Rejected",
    "voting.votingPower": "Voting Power",
    "voting.noVotingPower": "No voting power",
    "voting.titleColumn": "Title",
    "voting.stage": "Stage",
    "voting.status": "Status",
    "voting.votes": "Votes",
    "voting.remaining": "Remaining",
    "voting.noOngoing": "No ongoing votes",
    "voting.noEnded": "No ended votes",
    "voting.upvote": "Upvote",
    "voting.downvote": "Downvote",
    "voting.upvoteReaction": "Upvoted",
    "voting.downvoteReaction": "Downvoted",
    "voting.proposer": "Proposer",
    "voting.game": "Game",
    "voting.noProposals": "No proposals",
    "voting.noProposalsStatus": "No proposals",
    "voting.approvalDuration": "Voting Duration",
    "voting.preset": "Preset",
    "voting.custom": "Custom",
    "voting.days": "Days",
    "voting.hours": "Hours",
    "voting.minutes": "Minutes",
    "voting.participation": "Participation",
    "voting.onchain": "On-chain",
    "voting.voted": "Voted",
    "voting.decided": "Decided",
    "voting.revoteNeeded": "Revote Needed",
    "voting.noUserGames": "No user games",
    "voting.proposalDate": "Date",
    "voting.statusAdmin": "Status / Admin",
    "voting.upvoteDownvote": "Up/Down",
    "voting.proposalContent": "Content",
    "voting.loadFailed": "Failed to load voting list",
    "voting.approveConfirm": "Approve Proposal",
    "voting.startVoting": "Start Voting",
    "voting.voteDurationSet": "Please set voting duration",
    "voting.proposalApprovedVoting": "Proposal approved and voting started!",
    "voting.proposalApproved": "Proposal approved",
    "voting.proposalRejected": "Proposal rejected",
    "voting.adminRequired": "Admin permission required",
    "voting.connectWallet": "Please connect wallet",
    "voting.voteFailed": "Vote failed",
    "voting.voteError": "Error during voting",
    "voting.processingFailed": "Processing failed",
    "voting.voteResultApplied": "Vote result applied!",
    "voting.votingGuide": "Voting Guide",
    "voting.guide1": "Voting is only available during gameplay at the relevant choices",
    "voting.guide2": "On-chain votes: Permanently recorded on blockchain and transparently verifiable",
    "voting.guide3": "This page shows current voting status",
    "voting.guide4": "One vote per wallet address",
    "voting.guide5": "Only choices with majority votes can be selected in game",
    "voting.guide6": "Revote is required if no choice gets majority",
    "voting.daoContract": "VeryDAOIntegrated Contract",
    "voting.votingPeriod": "Voting Period",
    "voting.threeDays": "3 days",
    "voting.proposalRequirement": "Proposal Requirement",
    "voting.minVery": "Minimum 1 VERY",
    "voting.setting": "Setting",
    "voting.selectDuration": "Select Duration",
    "voting.customDuration": "Custom Duration",
    // Create Voting Modal
    "voting.createModal.title": "Create Vote",
    "voting.createModal.titleLabel": "Title *",
    "voting.createModal.titlePlaceholder": "Enter vote title",
    "voting.createModal.descLabel": "Description",
    "voting.createModal.descPlaceholder": "Enter description (optional)",
    "voting.createModal.stageLabel": "Stage *",
    "voting.createModal.stagePlaceholder": "Select a stage",
    "voting.createModal.choicesLabel": "Choices * (min 2)",
    "voting.createModal.noChoices": "No choices for this stage",
    "voting.createModal.duration": "Duration",
    "voting.createModal.hour": "hour",
    "voting.createModal.day": "day",
    "voting.createModal.creating": "Creating...",
    "voting.createModal.enterTitle": "Please enter title",
    "voting.createModal.selectStage": "Please select stage",
    "voting.createModal.minChoices": "Select at least 2 choices",
    "voting.createModal.created": "Vote created!",
    "voting.createModal.failed": "Failed to create vote",
    // Proposal Modal
    "voting.proposalModal.title": "Make Proposal",
    "voting.proposalModal.newProposal": "New Proposal",
    "voting.proposalModal.proposalList": "My Proposals",
    "voting.proposalModal.titleLabel": "Title *",
    "voting.proposalModal.titlePlaceholder": "What vote do you propose?",
    "voting.proposalModal.descLabel": "Description",
    "voting.proposalModal.descPlaceholder": "Enter detailed description (optional)",
    "voting.proposalModal.stageLabel": "Related Stage (optional)",
    "voting.proposalModal.stagePlaceholder": "Select a stage (optional)",
    "voting.proposalModal.costInfo": "Proposal requires",
    "voting.proposalModal.costAmount": "1 VERY",
    "voting.proposalModal.costSuffix": ".",
    "voting.proposalModal.reviewInfo": "Proposals are reviewed by admins before becoming votes.",
    "voting.proposalModal.submit": "Propose with 1 VERY",
    "voting.proposalModal.submitButton": "Propose with 1 VERY",
    "voting.proposalModal.submitting": "Submitting...",
    "voting.proposalModal.registering": "Registering proposal...",
    "voting.proposalModal.txPending": "Processing transaction...",
    "voting.proposalModal.txProcessing": "Processing transaction...",
    "voting.proposalModal.noProposals": "No proposals yet. Make the first one!",
    "voting.proposalModal.relatedStage": "Related Stage",
    "voting.proposalModal.enterTitle": "Please enter title",
    "voting.proposalModal.registered": "Proposal registered!",
    "voting.proposalModal.registerFailed": "Failed to register proposal",
    "voting.proposalModal.txFailed": "Transaction failed",
    "voting.proposalModal.txError": "Error during transaction",
    "voting.proposalModal.connectWallet": "Please connect wallet.",
    "voting.proposalModal.walletRejected": "Wallet connection rejected.",
    "voting.proposalModal.txApprove": "Please approve transaction...",
    "voting.proposalModal.noMetaMask": "MetaMask not detected.",
    "voting.proposalModal.veryMainnetFailed": "Failed to add VERY Mainnet.",
    "voting.proposalModal.switchVery": "Please switch to VERY Mainnet.",
    "voting.proposalModal.pendingStatus": "Pending",
    "voting.proposalModal.approvedStatus": "Approved",
    "voting.proposalModal.rejectedStatus": "Rejected",
    "voting.proposalModal.convertedStatus": "Converted to Vote",

    // Play Page
    "play.mainstream": "Mainstream",
    "play.mainStream": "Main Stream",
    "play.stream": "Stream",
    "play.createStream": "Create Stream",
    "play.create": "+ Create",
    "play.players": "Players",
    "play.era": "Era",
    "play.genre": "Genre",
    "play.plan": "Plan",
    "play.schedule": "Schedule",
    "play.title": "Title",
    "play.all": "ALL",
    "play.playDescription": "Play a variety of stream or create a new one.",
    "play.play": "Play",
    "play.free": "Free",
    "play.paid": "Paid",
    "play.unlimited": "Unlimited",
    "play.limited": "Limited",
    // Create Stream Modal
    "play.createModal.title": "Create a Stream",
    "play.createModal.titleLabel": "Title",
    "play.createModal.titlePlaceholder": "Enter stream title",
    "play.createModal.eraLabel": "Era",
    "play.createModal.eraPlaceholder": "Select era",
    "play.createModal.customEraPlaceholder": "Enter custom era",
    "play.createModal.genreLabel": "Genre",
    "play.createModal.genrePlaceholder": "Select genre",
    "play.createModal.customGenrePlaceholder": "Enter custom genre",
    "play.createModal.playersLabel": "Players",
    "play.createModal.playersPlaceholder": "Enter number of players",
    "play.createModal.planLabel": "Plan",
    "play.createModal.planFeePlaceholder": "Enter fee amount",
    "play.createModal.scheduleLabel": "Schedule",
    "play.createModal.monthly": "Monthly",
    "play.createModal.weekly": "Weekly",
    "play.createModal.daily": "Daily",
    "play.createModal.custom": "Custom",
    "play.createModal.customSchedulePlaceholder": "Enter custom schedule",
    "play.createModal.imageLabel": "Stream Image",
    "play.createModal.createSuccess": "Stream created successfully!",
    "play.createModal.createFailed": "Failed to create stream",
    "play.createModal.uploadImage": "Please upload a stream image",
    "play.createModal.uploadFailed": "Image upload failed",
    "play.createModal.unexpectedError": "An unexpected error occurred",
    "play.createModal.others": "Others",
    "play.createModal.week": "Week",
    // Game Filter
    "play.filter.era": "Era",
    "play.filter.genre": "Genre",
    "play.filter.players": "Players",
    "play.filter.free": "Free",
    "play.filter.all": "ALL",

    // Earn Page
    "earn.adsVery": "AdsVery",
    "earn.walletNotConnected": "Your wallet is not connected.",
    "earn.alreadyClaimed": "Already claimed today. Come back tomorrow!",
    "earn.pleaseWait": "Please wait a moment before clicking again.",
    "earn.claimed": "claimed!",
    "earn.noRewards": "No rewards to claim!",
    "earn.claimDone": "VTDN Claim Done",
    "earn.metamaskNotInstalled": "Metamask is not installed.",

    // Market Page
    "market.title": "NFT Marketplace",
    "market.connectWallet": "Connect your wallet to explore amazing NFTs",
    "market.marketplace": "Marketplace",
    "market.myCollection": "My Collection",
    "market.collections": "COLLECTIONS",
    "market.items": "Items",
    "market.availableForPurchase": "Available for purchase",
    "market.inYourWallet": "In your wallet",
    "market.search": "Search NFTs by name or token ID...",
    "market.recent": "Recent",
    "market.low": "Low",
    "market.high": "High",
    "market.highestPrice": "Highest Price",
    "market.lowestPrice": "Lowest Price",
    "market.connectedWith": "Connected with",
    "market.walletAddress": "Wallet Address",
    "market.disconnect": "Disconnect",
    "market.buy": "Buy",
    "market.sell": "Sell",
    "market.list": "List",
    "market.cancel": "Cancel",
    "market.price": "Price",
    "market.seller": "Seller",
    "market.quantity": "Quantity",
    "market.total": "Total",
    "market.category.all": "All",
    "market.category.weapon": "Weapon",
    "market.category.shoes": "Shoes",
    "market.category.gloves": "Gloves",
    "market.category.pants": "Pants",
    "market.category.top": "Top",
    "market.category.cloak": "Cloak",
    "market.category.helmet": "Helmet",
    "market.category.accessory": "Accessory",
    "market.category.title": "Title",
    "market.category.skill": "Skill",
    "market.listModal.title": "List NFT for Sale",
    "market.listModal.priceLabel": "Price (VERY)",
    "market.listModal.pricePlaceholder": "Enter sale price",
    "market.listModal.quantityLabel": "Quantity",
    "market.listModal.submit": "List",
    "market.listModal.submitting": "Listing...",
    "market.sellerModal.title": "Select Seller",
    "market.sellerModal.selectSeller": "Select a seller to purchase from",
    "market.sellerModal.quantity": "Quantity",
    "market.sellerModal.available": "Available",
    "market.sellerModal.buy": "Buy",
    "market.history.title": "Transaction History",
    "market.history.noHistory": "No transaction history",
    "market.history.bought": "Bought",
    "market.history.sold": "Sold",
    "market.history.listed": "Listed",
    "market.history.cancelled": "Cancelled",

    // Common
    "common.connect": "Connect",
    "common.disconnect": "Disconnect",
    "common.loading": "Loading...",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.all": "All",
  },
  ja: {
    // Navigation
    "nav.play": "プレイ",
    "nav.market": "マーケット",
    "nav.swap": "スワップ",
    "nav.earn": "獲得",
    "nav.voting": "投票",
    "nav.more": "その他",

    // Main Page
    "main.defineYourLegacy": "あなたの伝説を築け",
    "main.theEra": "時代",
    "main.genre": "ジャンル",
    "main.chooseYourPath": "あなたの道を選べ",

    // Voting Page
    "voting.title": "投票",
    "voting.subtitle": "投票で世界の運命を決めよう。",
    "voting.createVoting": "投票作成",
    "voting.proposal": "提案",
    "voting.ongoing": "進行中",
    "voting.ended": "終了",
    "voting.approve": "承認",
    "voting.reject": "却下",
    "voting.pending": "審査中",
    "voting.treasury": "トレジャリー",
    "voting.totalProposals": "総提案数",
    "voting.approved": "承認済み",
    "voting.rejected": "却下済み",
    "voting.noPermission": "ゲーム運営者のみ投票を作成できます",
    "voting.storyView": "ストーリービュー",
    "voting.daoView": "DAOビュー",
    "voting.mainstream": "メインストリーム",
    "voting.stream": "ストリーム",
    "voting.vtdnBalance": "VTDN残高",
    "voting.proposalCount": "提案",
    "voting.approvedCount": "承認",
    "voting.rejectedCount": "却下",
    "voting.votingPower": "投票力",
    "voting.noVotingPower": "投票力がありません",
    "voting.titleColumn": "タイトル",
    "voting.stage": "ステージ",
    "voting.status": "状態",
    "voting.votes": "投票",
    "voting.remaining": "残り時間",
    "voting.noOngoing": "進行中の投票がありません",
    "voting.noEnded": "終了した投票がありません",
    "voting.upvote": "賛成",
    "voting.downvote": "反対",
    "voting.upvoteReaction": "賛成しました",
    "voting.downvoteReaction": "反対しました",
    "voting.proposer": "提案者",
    "voting.game": "ゲーム",
    "voting.noProposals": "提案がありません",
    "voting.noProposalsStatus": "提案がありません",
    "voting.approvalDuration": "投票期間設定",
    "voting.preset": "プリセット",
    "voting.custom": "カスタム",
    "voting.days": "日",
    "voting.hours": "時間",
    "voting.minutes": "分",
    "voting.participation": "参加",
    "voting.onchain": "オンチェーン",
    "voting.voted": "投票済み",
    "voting.decided": "決定済み",
    "voting.revoteNeeded": "再投票が必要",
    "voting.noUserGames": "ユーザーゲームなし",
    "voting.proposalDate": "提案日",
    "voting.statusAdmin": "状態 / 管理",
    "voting.upvoteDownvote": "賛成/反対",
    "voting.proposalContent": "提案内容",
    "voting.loadFailed": "投票リストの読み込みに失敗しました",
    "voting.approveConfirm": "提案を承認",
    "voting.startVoting": "投票開始",
    "voting.voteDurationSet": "投票期間を設定してください",
    "voting.proposalApprovedVoting": "提案が承認され、投票が開始されました！",
    "voting.proposalApproved": "提案が承認されました",
    "voting.proposalRejected": "提案が却下されました",
    "voting.adminRequired": "管理者権限が必要です",
    "voting.connectWallet": "ウォレットを接続してください",
    "voting.voteFailed": "投票に失敗しました",
    "voting.voteError": "投票中にエラーが発生しました",
    "voting.processingFailed": "処理に失敗しました",
    "voting.voteResultApplied": "投票結果が反映されました！",
    "voting.votingGuide": "投票ガイド",
    "voting.guide1": "投票はゲームプレイ中の該当選択肢でのみ可能です",
    "voting.guide2": "オンチェーン投票：ブロックチェーンに永久記録され、透明性が保証されます",
    "voting.guide3": "このページでは現在の投票状況を確認できます",
    "voting.guide4": "ウォレットアドレスごとに1票投票可能",
    "voting.guide5": "投票終了後、過半数を獲得した選択肢のみゲームで選択可能",
    "voting.guide6": "過半数を獲得できない場合は再投票が必要です",
    "voting.daoContract": "VeryDAOIntegrated コントラクト",
    "voting.votingPeriod": "投票期間",
    "voting.threeDays": "3日間",
    "voting.proposalRequirement": "提案条件",
    "voting.minVery": "最低1 VERY必要",
    "voting.setting": "設定",
    "voting.selectDuration": "期間を選択",
    "voting.customDuration": "カスタム期間",
    // Create Voting Modal
    "voting.createModal.title": "投票作成",
    "voting.createModal.titleLabel": "タイトル *",
    "voting.createModal.titlePlaceholder": "投票タイトルを入力",
    "voting.createModal.descLabel": "説明",
    "voting.createModal.descPlaceholder": "説明を入力（任意）",
    "voting.createModal.stageLabel": "ステージ *",
    "voting.createModal.stagePlaceholder": "ステージを選択",
    "voting.createModal.choicesLabel": "選択肢 *（最低2つ）",
    "voting.createModal.noChoices": "このステージに選択肢がありません",
    "voting.createModal.duration": "期間",
    "voting.createModal.hour": "時間",
    "voting.createModal.day": "日",
    "voting.createModal.creating": "作成中...",
    "voting.createModal.enterTitle": "タイトルを入力してください",
    "voting.createModal.selectStage": "ステージを選択してください",
    "voting.createModal.minChoices": "最低2つの選択肢を選んでください",
    "voting.createModal.created": "投票が作成されました！",
    "voting.createModal.failed": "投票の作成に失敗しました",
    // Proposal Modal
    "voting.proposalModal.title": "提案する",
    "voting.proposalModal.newProposal": "新規提案",
    "voting.proposalModal.proposalList": "提案リスト",
    "voting.proposalModal.titleLabel": "タイトル *",
    "voting.proposalModal.titlePlaceholder": "どんな投票を提案しますか？",
    "voting.proposalModal.descLabel": "詳細説明",
    "voting.proposalModal.descPlaceholder": "詳細な説明を入力（任意）",
    "voting.proposalModal.stageLabel": "関連ステージ（任意）",
    "voting.proposalModal.stagePlaceholder": "ステージを選択（任意）",
    "voting.proposalModal.costInfo": "提案には",
    "voting.proposalModal.costAmount": "1 VERY",
    "voting.proposalModal.costSuffix": "が必要です。",
    "voting.proposalModal.reviewInfo": "提案は管理者の審査後に投票に変換されます。",
    "voting.proposalModal.submit": "1 VERYで提案",
    "voting.proposalModal.submitButton": "1 VERYで提案",
    "voting.proposalModal.submitting": "提出中...",
    "voting.proposalModal.registering": "提案登録中...",
    "voting.proposalModal.txPending": "トランザクション処理中...",
    "voting.proposalModal.txProcessing": "トランザクション処理中...",
    "voting.proposalModal.noProposals": "まだ提案がありません。最初の提案をしましょう！",
    "voting.proposalModal.relatedStage": "関連ステージ",
    "voting.proposalModal.enterTitle": "タイトルを入力してください",
    "voting.proposalModal.registered": "提案が登録されました！",
    "voting.proposalModal.registerFailed": "提案の登録に失敗しました",
    "voting.proposalModal.txFailed": "トランザクションが失敗しました",
    "voting.proposalModal.txError": "トランザクション中にエラーが発生しました",
    "voting.proposalModal.connectWallet": "ウォレットを接続してください。",
    "voting.proposalModal.walletRejected": "ウォレット接続が拒否されました。",
    "voting.proposalModal.txApprove": "トランザクションを承認してください...",
    "voting.proposalModal.noMetaMask": "MetaMaskが検出されません。",
    "voting.proposalModal.veryMainnetFailed": "VERY メインネット追加に失敗しました。",
    "voting.proposalModal.switchVery": "VERY メインネットに切り替えてください。",
    "voting.proposalModal.pendingStatus": "審査中",
    "voting.proposalModal.approvedStatus": "承認済み",
    "voting.proposalModal.rejectedStatus": "却下済み",
    "voting.proposalModal.convertedStatus": "投票に変換済み",

    // Play Page
    "play.mainstream": "メインストリーム",
    "play.mainStream": "メインストリーム",
    "play.stream": "ストリーム",
    "play.createStream": "ストリーム作成",
    "play.create": "+ 作成",
    "play.players": "プレイヤー",
    "play.era": "時代",
    "play.genre": "ジャンル",
    "play.plan": "プラン",
    "play.schedule": "スケジュール",
    "play.title": "タイトル",
    "play.all": "すべて",
    "play.playDescription": "様々なストリームをプレイするか、新しいものを作成してください。",
    "play.play": "プレイ",
    "play.free": "無料",
    "play.paid": "有料",
    "play.unlimited": "無制限",
    "play.limited": "制限あり",
    // Create Stream Modal
    "play.createModal.title": "ストリーム作成",
    "play.createModal.titleLabel": "タイトル",
    "play.createModal.titlePlaceholder": "ストリームタイトルを入力",
    "play.createModal.eraLabel": "時代",
    "play.createModal.eraPlaceholder": "時代を選択",
    "play.createModal.customEraPlaceholder": "カスタム時代を入力",
    "play.createModal.genreLabel": "ジャンル",
    "play.createModal.genrePlaceholder": "ジャンルを選択",
    "play.createModal.customGenrePlaceholder": "カスタムジャンルを入力",
    "play.createModal.playersLabel": "プレイヤー",
    "play.createModal.playersPlaceholder": "プレイヤー数を入力",
    "play.createModal.planLabel": "プラン",
    "play.createModal.planFeePlaceholder": "料金を入力",
    "play.createModal.scheduleLabel": "スケジュール",
    "play.createModal.monthly": "毎月",
    "play.createModal.weekly": "毎週",
    "play.createModal.daily": "毎日",
    "play.createModal.custom": "カスタム",
    "play.createModal.customSchedulePlaceholder": "カスタムスケジュールを入力",
    "play.createModal.imageLabel": "ストリーム画像",
    "play.createModal.createSuccess": "ストリームが作成されました！",
    "play.createModal.createFailed": "ストリームの作成に失敗しました",
    "play.createModal.uploadImage": "ストリーム画像をアップロードしてください",
    "play.createModal.uploadFailed": "画像のアップロードに失敗しました",
    "play.createModal.unexpectedError": "予期しないエラーが発生しました",
    "play.createModal.others": "その他",
    "play.createModal.week": "週目",
    // Game Filter
    "play.filter.era": "時代",
    "play.filter.genre": "ジャンル",
    "play.filter.players": "プレイヤー",
    "play.filter.free": "無料",
    "play.filter.all": "すべて",

    // Earn Page
    "earn.adsVery": "AdsVery",
    "earn.walletNotConnected": "ウォレットが接続されていません。",
    "earn.alreadyClaimed": "今日は既に受け取りました。明日また来てください！",
    "earn.pleaseWait": "しばらくしてからもう一度クリックしてください。",
    "earn.claimed": "受け取り完了！",
    "earn.noRewards": "受け取れる報酬がありません！",
    "earn.claimDone": "VTDN受け取り完了",
    "earn.metamaskNotInstalled": "Metamaskがインストールされていません。",

    // Market Page
    "market.title": "NFTマーケットプレイス",
    "market.connectWallet": "ウォレットを接続して素晴らしいNFTを探索",
    "market.marketplace": "マーケットプレイス",
    "market.myCollection": "マイコレクション",
    "market.collections": "コレクション",
    "market.items": "アイテム",
    "market.availableForPurchase": "購入可能",
    "market.inYourWallet": "ウォレット内",
    "market.search": "名前またはトークンIDでNFTを検索...",
    "market.recent": "最新",
    "market.low": "安い順",
    "market.high": "高い順",
    "market.highestPrice": "最高価格",
    "market.lowestPrice": "最低価格",
    "market.connectedWith": "接続済み",
    "market.walletAddress": "ウォレットアドレス",
    "market.disconnect": "切断",
    "market.buy": "購入",
    "market.sell": "販売",
    "market.list": "出品",
    "market.cancel": "キャンセル",
    "market.price": "価格",
    "market.seller": "販売者",
    "market.quantity": "数量",
    "market.total": "合計",
    "market.category.all": "すべて",
    "market.category.weapon": "武器",
    "market.category.shoes": "靴",
    "market.category.gloves": "手袋",
    "market.category.pants": "パンツ",
    "market.category.top": "トップス",
    "market.category.cloak": "マント",
    "market.category.helmet": "兜",
    "market.category.accessory": "アクセサリー",
    "market.category.title": "称号",
    "market.category.skill": "スキル",
    "market.listModal.title": "NFT出品",
    "market.listModal.priceLabel": "価格 (VERY)",
    "market.listModal.pricePlaceholder": "販売価格を入力",
    "market.listModal.quantityLabel": "数量",
    "market.listModal.submit": "出品する",
    "market.listModal.submitting": "出品中...",
    "market.sellerModal.title": "販売者を選択",
    "market.sellerModal.selectSeller": "購入する販売者を選択",
    "market.sellerModal.quantity": "数量",
    "market.sellerModal.available": "利用可能",
    "market.sellerModal.buy": "購入",
    "market.history.title": "取引履歴",
    "market.history.noHistory": "取引履歴なし",
    "market.history.bought": "購入",
    "market.history.sold": "販売",
    "market.history.listed": "出品",
    "market.history.cancelled": "キャンセル",

    // Common
    "common.connect": "接続",
    "common.disconnect": "切断",
    "common.loading": "読み込み中...",
    "common.confirm": "確認",
    "common.cancel": "キャンセル",
    "common.save": "保存",
    "common.delete": "削除",
    "common.edit": "編集",
    "common.search": "検索",
    "common.filter": "フィルター",
    "common.all": "すべて",
  },
  zh: {
    // Navigation
    "nav.play": "游戏",
    "nav.market": "市场",
    "nav.swap": "交换",
    "nav.earn": "赚取",
    "nav.voting": "投票",
    "nav.more": "更多",

    // Main Page
    "main.defineYourLegacy": "定义你的传奇",
    "main.theEra": "时代",
    "main.genre": "类型",
    "main.chooseYourPath": "选择你的道路",

    // Voting Page
    "voting.title": "投票",
    "voting.subtitle": "用投票决定世界的命运。",
    "voting.createVoting": "创建投票",
    "voting.proposal": "提案",
    "voting.ongoing": "进行中",
    "voting.ended": "已结束",
    "voting.approve": "批准",
    "voting.reject": "拒绝",
    "voting.pending": "审核中",
    "voting.treasury": "国库",
    "voting.totalProposals": "总提案",
    "voting.approved": "已批准",
    "voting.rejected": "已拒绝",
    "voting.noPermission": "只有游戏运营者才能创建投票",
    "voting.storyView": "故事视图",
    "voting.daoView": "DAO视图",
    "voting.mainstream": "主流",
    "voting.stream": "直播",
    "voting.vtdnBalance": "VTDN余额",
    "voting.proposalCount": "提案",
    "voting.approvedCount": "批准",
    "voting.rejectedCount": "拒绝",
    "voting.votingPower": "投票权",
    "voting.noVotingPower": "没有投票权",
    "voting.titleColumn": "标题",
    "voting.stage": "阶段",
    "voting.status": "状态",
    "voting.votes": "票数",
    "voting.remaining": "剩余时间",
    "voting.noOngoing": "没有进行中的投票",
    "voting.noEnded": "没有已结束的投票",
    "voting.upvote": "赞成",
    "voting.downvote": "反对",
    "voting.upvoteReaction": "已赞成",
    "voting.downvoteReaction": "已反对",
    "voting.proposer": "提案者",
    "voting.game": "游戏",
    "voting.noProposals": "没有提案",
    "voting.noProposalsStatus": "没有提案",
    "voting.approvalDuration": "投票期限设置",
    "voting.preset": "预设",
    "voting.custom": "自定义",
    "voting.days": "天",
    "voting.hours": "小时",
    "voting.minutes": "分钟",
    "voting.participation": "参与",
    "voting.onchain": "链上",
    "voting.voted": "已投票",
    "voting.decided": "已决定",
    "voting.revoteNeeded": "需要重新投票",
    "voting.noUserGames": "没有用户游戏",
    "voting.proposalDate": "提案日期",
    "voting.statusAdmin": "状态 / 管理",
    "voting.upvoteDownvote": "赞成/反对",
    "voting.proposalContent": "提案内容",
    "voting.loadFailed": "加载投票列表失败",
    "voting.approveConfirm": "批准提案",
    "voting.startVoting": "开始投票",
    "voting.voteDurationSet": "请设置投票期限",
    "voting.proposalApprovedVoting": "提案已批准，投票开始！",
    "voting.proposalApproved": "提案已批准",
    "voting.proposalRejected": "提案已拒绝",
    "voting.adminRequired": "需要管理员权限",
    "voting.connectWallet": "请连接钱包",
    "voting.voteFailed": "投票失败",
    "voting.voteError": "投票时发生错误",
    "voting.processingFailed": "处理失败",
    "voting.voteResultApplied": "投票结果已应用！",
    "voting.votingGuide": "投票指南",
    "voting.guide1": "投票仅在游戏过程中的相关选项处可用",
    "voting.guide2": "链上投票：永久记录在区块链上，可透明验证",
    "voting.guide3": "此页面显示当前投票状态",
    "voting.guide4": "每个钱包地址可投一票",
    "voting.guide5": "投票结束后，只有获得多数票的选项可在游戏中选择",
    "voting.guide6": "如果没有选项获得多数票，需要重新投票",
    "voting.daoContract": "VeryDAOIntegrated 合约",
    "voting.votingPeriod": "投票期限",
    "voting.threeDays": "3天",
    "voting.proposalRequirement": "提案条件",
    "voting.minVery": "最少持有1 VERY",
    "voting.setting": "设置",
    "voting.selectDuration": "选择期限",
    "voting.customDuration": "自定义期限",
    // Create Voting Modal
    "voting.createModal.title": "创建投票",
    "voting.createModal.titleLabel": "标题 *",
    "voting.createModal.titlePlaceholder": "输入投票标题",
    "voting.createModal.descLabel": "描述",
    "voting.createModal.descPlaceholder": "输入描述（可选）",
    "voting.createModal.stageLabel": "阶段 *",
    "voting.createModal.stagePlaceholder": "选择阶段",
    "voting.createModal.choicesLabel": "选项 *（至少2个）",
    "voting.createModal.noChoices": "此阶段没有选项",
    "voting.createModal.duration": "期限",
    "voting.createModal.hour": "小时",
    "voting.createModal.day": "天",
    "voting.createModal.creating": "创建中...",
    "voting.createModal.enterTitle": "请输入标题",
    "voting.createModal.selectStage": "请选择阶段",
    "voting.createModal.minChoices": "请至少选择2个选项",
    "voting.createModal.created": "投票已创建！",
    "voting.createModal.failed": "创建投票失败",
    // Proposal Modal
    "voting.proposalModal.title": "提交提案",
    "voting.proposalModal.newProposal": "新提案",
    "voting.proposalModal.proposalList": "提案列表",
    "voting.proposalModal.titleLabel": "标题 *",
    "voting.proposalModal.titlePlaceholder": "您想提议什么投票？",
    "voting.proposalModal.descLabel": "详细描述",
    "voting.proposalModal.descPlaceholder": "输入详细描述（可选）",
    "voting.proposalModal.stageLabel": "相关阶段（可选）",
    "voting.proposalModal.stagePlaceholder": "选择阶段（可选）",
    "voting.proposalModal.costInfo": "提案需要",
    "voting.proposalModal.costAmount": "1 VERY",
    "voting.proposalModal.costSuffix": "。",
    "voting.proposalModal.reviewInfo": "提案经管理员审核后转为投票。",
    "voting.proposalModal.submit": "用1 VERY提案",
    "voting.proposalModal.submitButton": "用1 VERY提案",
    "voting.proposalModal.submitting": "提交中...",
    "voting.proposalModal.registering": "提案注册中...",
    "voting.proposalModal.txPending": "交易处理中...",
    "voting.proposalModal.txProcessing": "交易处理中...",
    "voting.proposalModal.noProposals": "还没有提案。成为第一个！",
    "voting.proposalModal.relatedStage": "相关阶段",
    "voting.proposalModal.enterTitle": "请输入标题",
    "voting.proposalModal.registered": "提案已注册！",
    "voting.proposalModal.registerFailed": "提案注册失败",
    "voting.proposalModal.txFailed": "交易失败",
    "voting.proposalModal.txError": "交易时发生错误",
    "voting.proposalModal.connectWallet": "请连接钱包。",
    "voting.proposalModal.walletRejected": "钱包连接被拒绝。",
    "voting.proposalModal.txApprove": "请批准交易...",
    "voting.proposalModal.noMetaMask": "未检测到MetaMask。",
    "voting.proposalModal.veryMainnetFailed": "添加VERY主网失败。",
    "voting.proposalModal.switchVery": "请切换到VERY主网。",
    "voting.proposalModal.pendingStatus": "审核中",
    "voting.proposalModal.approvedStatus": "已批准",
    "voting.proposalModal.rejectedStatus": "已拒绝",
    "voting.proposalModal.convertedStatus": "已转为投票",

    // Play Page
    "play.mainstream": "主流",
    "play.mainStream": "主流",
    "play.stream": "直播",
    "play.createStream": "创建直播",
    "play.create": "+ 创建",
    "play.players": "玩家",
    "play.era": "时代",
    "play.genre": "类型",
    "play.plan": "方案",
    "play.schedule": "时间表",
    "play.title": "标题",
    "play.all": "全部",
    "play.playDescription": "玩各种直播或创建新的直播。",
    "play.play": "玩",
    "play.free": "免费",
    "play.paid": "付费",
    "play.unlimited": "无限",
    "play.limited": "有限",
    // Create Stream Modal
    "play.createModal.title": "创建直播",
    "play.createModal.titleLabel": "标题",
    "play.createModal.titlePlaceholder": "输入直播标题",
    "play.createModal.eraLabel": "时代",
    "play.createModal.eraPlaceholder": "选择时代",
    "play.createModal.customEraPlaceholder": "输入自定义时代",
    "play.createModal.genreLabel": "类型",
    "play.createModal.genrePlaceholder": "选择类型",
    "play.createModal.customGenrePlaceholder": "输入自定义类型",
    "play.createModal.playersLabel": "玩家",
    "play.createModal.playersPlaceholder": "输入玩家数量",
    "play.createModal.planLabel": "方案",
    "play.createModal.planFeePlaceholder": "输入费用",
    "play.createModal.scheduleLabel": "时间表",
    "play.createModal.monthly": "每月",
    "play.createModal.weekly": "每周",
    "play.createModal.daily": "每天",
    "play.createModal.custom": "自定义",
    "play.createModal.customSchedulePlaceholder": "输入自定义时间表",
    "play.createModal.imageLabel": "直播图片",
    "play.createModal.createSuccess": "直播创建成功！",
    "play.createModal.createFailed": "创建直播失败",
    "play.createModal.uploadImage": "请上传直播图片",
    "play.createModal.uploadFailed": "图片上传失败",
    "play.createModal.unexpectedError": "发生意外错误",
    "play.createModal.others": "其他",
    "play.createModal.week": "周",
    // Game Filter
    "play.filter.era": "时代",
    "play.filter.genre": "类型",
    "play.filter.players": "玩家",
    "play.filter.free": "免费",
    "play.filter.all": "全部",

    // Earn Page
    "earn.adsVery": "AdsVery",
    "earn.walletNotConnected": "钱包未连接。",
    "earn.alreadyClaimed": "今天已领取。明天再来吧！",
    "earn.pleaseWait": "请稍等后再点击。",
    "earn.claimed": "领取成功！",
    "earn.noRewards": "没有可领取的奖励！",
    "earn.claimDone": "VTDN领取完成",
    "earn.metamaskNotInstalled": "未安装Metamask。",

    // Market Page
    "market.title": "NFT市场",
    "market.connectWallet": "连接钱包探索精彩NFT",
    "market.marketplace": "市场",
    "market.myCollection": "我的收藏",
    "market.collections": "收藏品",
    "market.items": "个物品",
    "market.availableForPurchase": "可购买",
    "market.inYourWallet": "在您的钱包中",
    "market.search": "按名称或代币ID搜索NFT...",
    "market.recent": "最新",
    "market.low": "低价",
    "market.high": "高价",
    "market.highestPrice": "最高价",
    "market.lowestPrice": "最低价",
    "market.connectedWith": "已连接",
    "market.walletAddress": "钱包地址",
    "market.disconnect": "断开",
    "market.buy": "购买",
    "market.sell": "出售",
    "market.list": "上架",
    "market.cancel": "取消",
    "market.price": "价格",
    "market.seller": "卖家",
    "market.quantity": "数量",
    "market.total": "总计",
    "market.category.all": "全部",
    "market.category.weapon": "武器",
    "market.category.shoes": "鞋子",
    "market.category.gloves": "手套",
    "market.category.pants": "裤子",
    "market.category.top": "上衣",
    "market.category.cloak": "披风",
    "market.category.helmet": "头盔",
    "market.category.accessory": "饰品",
    "market.category.title": "称号",
    "market.category.skill": "技能",
    "market.listModal.title": "上架NFT",
    "market.listModal.priceLabel": "价格 (VERY)",
    "market.listModal.pricePlaceholder": "输入销售价格",
    "market.listModal.quantityLabel": "数量",
    "market.listModal.submit": "上架",
    "market.listModal.submitting": "上架中...",
    "market.sellerModal.title": "选择卖家",
    "market.sellerModal.selectSeller": "选择购买的卖家",
    "market.sellerModal.quantity": "数量",
    "market.sellerModal.available": "可用",
    "market.sellerModal.buy": "购买",
    "market.history.title": "交易历史",
    "market.history.noHistory": "暂无交易历史",
    "market.history.bought": "购买",
    "market.history.sold": "出售",
    "market.history.listed": "上架",
    "market.history.cancelled": "取消",

    // Common
    "common.connect": "连接",
    "common.disconnect": "断开",
    "common.loading": "加载中...",
    "common.confirm": "确认",
    "common.cancel": "取消",
    "common.save": "保存",
    "common.delete": "删除",
    "common.edit": "编辑",
    "common.search": "搜索",
    "common.filter": "筛选",
    "common.all": "全部",
  },
  tr: {
    // Navigation
    "nav.play": "Oyna",
    "nav.market": "Market",
    "nav.swap": "Takas",
    "nav.earn": "Kazan",
    "nav.voting": "Oylama",
    "nav.more": "Daha Fazla",

    // Main Page
    "main.defineYourLegacy": "MİRASINI BELİRLE",
    "main.theEra": "DÖNEM",
    "main.genre": "TÜR",
    "main.chooseYourPath": "YOLUNU SEÇ",

    // Voting Page
    "voting.title": "Oylama",
    "voting.subtitle": "Oylama ile dünyanın kaderini belirle.",
    "voting.createVoting": "Oylama Oluştur",
    "voting.proposal": "Öneri",
    "voting.ongoing": "Devam Eden",
    "voting.ended": "Sona Erdi",
    "voting.approve": "Onayla",
    "voting.reject": "Reddet",
    "voting.pending": "Beklemede",
    "voting.treasury": "Hazine",
    "voting.totalProposals": "Toplam Öneriler",
    "voting.approved": "Onaylandı",
    "voting.rejected": "Reddedildi",
    "voting.noPermission": "Sadece oyun operatörleri oy oluşturabilir",
    "voting.storyView": "Hikaye Görünümü",
    "voting.daoView": "DAO Görünümü",
    "voting.mainstream": "Ana Akım",
    "voting.stream": "Yayın",
    "voting.vtdnBalance": "VTDN Bakiyesi",
    "voting.proposalCount": "Öneri",
    "voting.approvedCount": "Onaylanan",
    "voting.rejectedCount": "Reddedilen",
    "voting.votingPower": "Oy Gücü",
    "voting.noVotingPower": "Oy gücünüz yok",
    "voting.titleColumn": "Başlık",
    "voting.stage": "Aşama",
    "voting.status": "Durum",
    "voting.votes": "Oylar",
    "voting.remaining": "Kalan Süre",
    "voting.noOngoing": "Devam eden oylama yok",
    "voting.noEnded": "Sona eren oylama yok",
    "voting.upvote": "Beğen",
    "voting.downvote": "Beğenme",
    "voting.upvoteReaction": "Beğendiniz",
    "voting.downvoteReaction": "Beğenmediniz",
    "voting.proposer": "Öneren",
    "voting.game": "Oyun",
    "voting.noProposals": "Öneri yok",
    "voting.noProposalsStatus": "Öneri yok",
    "voting.approvalDuration": "Oylama Süresi Ayarı",
    "voting.preset": "Ön Ayar",
    "voting.custom": "Özel",
    "voting.days": "Gün",
    "voting.hours": "Saat",
    "voting.minutes": "Dakika",
    "voting.participation": "Katılım",
    "voting.onchain": "Zincir Üstü",
    "voting.voted": "Oy Verildi",
    "voting.decided": "Karar Verildi",
    "voting.revoteNeeded": "Yeniden Oylama Gerekli",
    "voting.noUserGames": "Kullanıcı oyunu yok",
    "voting.proposalDate": "Öneri Tarihi",
    "voting.statusAdmin": "Durum / Yönetim",
    "voting.upvoteDownvote": "Beğen/Beğenme",
    "voting.proposalContent": "Öneri İçeriği",
    "voting.loadFailed": "Oylama listesi yüklenemedi",
    "voting.approveConfirm": "Öneriyi Onayla",
    "voting.startVoting": "Oylamayı Başlat",
    "voting.voteDurationSet": "Lütfen oylama süresini ayarlayın",
    "voting.proposalApprovedVoting": "Öneri onaylandı ve oylama başladı!",
    "voting.proposalApproved": "Öneri onaylandı",
    "voting.proposalRejected": "Öneri reddedildi",
    "voting.adminRequired": "Yönetici izni gerekli",
    "voting.connectWallet": "Lütfen cüzdan bağlayın",
    "voting.voteFailed": "Oylama başarısız",
    "voting.voteError": "Oylama sırasında hata oluştu",
    "voting.processingFailed": "İşlem başarısız",
    "voting.voteResultApplied": "Oylama sonucu uygulandı!",
    "voting.votingGuide": "Oylama Rehberi",
    "voting.guide1": "Oylama yalnızca oyun sırasında ilgili seçeneklerde mümkündür",
    "voting.guide2": "Zincir üstü oylama: Blockchain'de kalıcı olarak kaydedilir ve şeffaf bir şekilde doğrulanabilir",
    "voting.guide3": "Bu sayfa mevcut oylama durumunu gösterir",
    "voting.guide4": "Cüzdan adresi başına bir oy",
    "voting.guide5": "Oylama sonunda yalnızca çoğunluk oyu alan seçenek oyunda seçilebilir",
    "voting.guide6": "Hiçbir seçenek çoğunluk alamazsa yeniden oylama gerekir",
    "voting.daoContract": "VeryDAOIntegrated Sözleşmesi",
    "voting.votingPeriod": "Oylama Süresi",
    "voting.threeDays": "3 gün",
    "voting.proposalRequirement": "Öneri Koşulu",
    "voting.minVery": "En az 1 VERY gerekli",
    "voting.setting": "Ayar",
    "voting.selectDuration": "Süre Seç",
    "voting.customDuration": "Özel Süre",
    // Create Voting Modal
    "voting.createModal.title": "Oylama Oluştur",
    "voting.createModal.titleLabel": "Başlık *",
    "voting.createModal.titlePlaceholder": "Oylama başlığını girin",
    "voting.createModal.descLabel": "Açıklama",
    "voting.createModal.descPlaceholder": "Açıklama girin (isteğe bağlı)",
    "voting.createModal.stageLabel": "Aşama *",
    "voting.createModal.stagePlaceholder": "Aşama seçin",
    "voting.createModal.choicesLabel": "Seçenekler * (en az 2)",
    "voting.createModal.noChoices": "Bu aşamada seçenek yok",
    "voting.createModal.duration": "Süre",
    "voting.createModal.hour": "saat",
    "voting.createModal.day": "gün",
    "voting.createModal.creating": "Oluşturuluyor...",
    "voting.createModal.enterTitle": "Lütfen başlık girin",
    "voting.createModal.selectStage": "Lütfen aşama seçin",
    "voting.createModal.minChoices": "En az 2 seçenek seçin",
    "voting.createModal.created": "Oylama oluşturuldu!",
    "voting.createModal.failed": "Oylama oluşturulamadı",
    // Proposal Modal
    "voting.proposalModal.title": "Öneri Yap",
    "voting.proposalModal.newProposal": "Yeni Öneri",
    "voting.proposalModal.proposalList": "Önerilerim",
    "voting.proposalModal.titleLabel": "Başlık *",
    "voting.proposalModal.titlePlaceholder": "Ne oylaması öneriyorsunuz?",
    "voting.proposalModal.descLabel": "Açıklama",
    "voting.proposalModal.descPlaceholder": "Detaylı açıklama girin (isteğe bağlı)",
    "voting.proposalModal.stageLabel": "İlgili Aşama (isteğe bağlı)",
    "voting.proposalModal.stagePlaceholder": "Aşama seçin (isteğe bağlı)",
    "voting.proposalModal.costInfo": "Öneri için",
    "voting.proposalModal.costAmount": "1 VERY",
    "voting.proposalModal.costSuffix": " gerekli.",
    "voting.proposalModal.reviewInfo": "Öneriler yöneticiler tarafından incelendikten sonra oylamaya dönüştürülür.",
    "voting.proposalModal.submit": "1 VERY ile Öner",
    "voting.proposalModal.submitButton": "1 VERY ile Öner",
    "voting.proposalModal.submitting": "Gönderiliyor...",
    "voting.proposalModal.registering": "Öneri kaydediliyor...",
    "voting.proposalModal.txPending": "İşlem işleniyor...",
    "voting.proposalModal.txProcessing": "İşlem işleniyor...",
    "voting.proposalModal.noProposals": "Henüz öneri yok. İlk siz olun!",
    "voting.proposalModal.relatedStage": "İlgili Aşama",
    "voting.proposalModal.enterTitle": "Lütfen başlık girin",
    "voting.proposalModal.registered": "Öneri kaydedildi!",
    "voting.proposalModal.registerFailed": "Öneri kaydedilemedi",
    "voting.proposalModal.txFailed": "İşlem başarısız",
    "voting.proposalModal.txError": "İşlem sırasında hata oluştu",
    "voting.proposalModal.connectWallet": "Lütfen cüzdan bağlayın.",
    "voting.proposalModal.walletRejected": "Cüzdan bağlantısı reddedildi.",
    "voting.proposalModal.txApprove": "Lütfen işlemi onaylayın...",
    "voting.proposalModal.noMetaMask": "MetaMask algılanamadı.",
    "voting.proposalModal.veryMainnetFailed": "VERY Mainnet eklenemedi.",
    "voting.proposalModal.switchVery": "Lütfen VERY Mainnet'e geçin.",
    "voting.proposalModal.pendingStatus": "Beklemede",
    "voting.proposalModal.approvedStatus": "Onaylandı",
    "voting.proposalModal.rejectedStatus": "Reddedildi",
    "voting.proposalModal.convertedStatus": "Oylamaya Dönüştürüldü",

    // Play Page
    "play.mainstream": "Ana Akım",
    "play.mainStream": "Ana Akım",
    "play.stream": "Yayın",
    "play.createStream": "Yayın Oluştur",
    "play.create": "+ Oluştur",
    "play.players": "Oyuncular",
    "play.era": "Dönem",
    "play.genre": "Tür",
    "play.plan": "Plan",
    "play.schedule": "Program",
    "play.title": "Başlık",
    "play.all": "TÜMÜ",
    "play.playDescription": "Çeşitli yayınları oynayın veya yeni bir tane oluşturun.",
    "play.play": "Oyna",
    "play.free": "Ücretsiz",
    "play.paid": "Ücretli",
    "play.unlimited": "Sınırsız",
    "play.limited": "Sınırlı",
    // Create Stream Modal
    "play.createModal.title": "Yayın Oluştur",
    "play.createModal.titleLabel": "Başlık",
    "play.createModal.titlePlaceholder": "Yayın başlığını girin",
    "play.createModal.eraLabel": "Dönem",
    "play.createModal.eraPlaceholder": "Dönem seçin",
    "play.createModal.customEraPlaceholder": "Özel dönem girin",
    "play.createModal.genreLabel": "Tür",
    "play.createModal.genrePlaceholder": "Tür seçin",
    "play.createModal.customGenrePlaceholder": "Özel tür girin",
    "play.createModal.playersLabel": "Oyuncular",
    "play.createModal.playersPlaceholder": "Oyuncu sayısını girin",
    "play.createModal.planLabel": "Plan",
    "play.createModal.planFeePlaceholder": "Ücret miktarını girin",
    "play.createModal.scheduleLabel": "Program",
    "play.createModal.monthly": "Aylık",
    "play.createModal.weekly": "Haftalık",
    "play.createModal.daily": "Günlük",
    "play.createModal.custom": "Özel",
    "play.createModal.customSchedulePlaceholder": "Özel program girin",
    "play.createModal.imageLabel": "Yayın Resmi",
    "play.createModal.createSuccess": "Yayın başarıyla oluşturuldu!",
    "play.createModal.createFailed": "Yayın oluşturulamadı",
    "play.createModal.uploadImage": "Lütfen yayın resmi yükleyin",
    "play.createModal.uploadFailed": "Resim yüklenemedi",
    "play.createModal.unexpectedError": "Beklenmeyen bir hata oluştu",
    "play.createModal.others": "Diğer",
    "play.createModal.week": "Hafta",
    // Game Filter
    "play.filter.era": "Dönem",
    "play.filter.genre": "Tür",
    "play.filter.players": "Oyuncular",
    "play.filter.free": "Ücretsiz",
    "play.filter.all": "TÜMÜ",

    // Earn Page
    "earn.adsVery": "AdsVery",
    "earn.walletNotConnected": "Cüzdanınız bağlı değil.",
    "earn.alreadyClaimed": "Bugün zaten alındı. Yarın tekrar gelin!",
    "earn.pleaseWait": "Lütfen tekrar tıklamadan önce bekleyin.",
    "earn.claimed": "alındı!",
    "earn.noRewards": "Alınacak ödül yok!",
    "earn.claimDone": "VTDN Alma Tamamlandı",
    "earn.metamaskNotInstalled": "Metamask yüklü değil.",

    // Market Page
    "market.title": "NFT Pazarı",
    "market.connectWallet": "Harika NFT'leri keşfetmek için cüzdanınızı bağlayın",
    "market.marketplace": "Pazar",
    "market.myCollection": "Koleksiyonum",
    "market.collections": "Koleksiyonlar",
    "market.items": "Öğe",
    "market.availableForPurchase": "Satın alınabilir",
    "market.inYourWallet": "Cüzdanınızda",
    "market.search": "NFT'leri ada veya token ID'ye göre ara...",
    "market.recent": "Son",
    "market.low": "Düşük",
    "market.high": "Yüksek",
    "market.highestPrice": "En Yüksek Fiyat",
    "market.lowestPrice": "En Düşük Fiyat",
    "market.connectedWith": "Bağlı",
    "market.walletAddress": "Cüzdan Adresi",
    "market.disconnect": "Bağlantıyı Kes",
    "market.buy": "Satın Al",
    "market.sell": "Sat",
    "market.list": "Listele",
    "market.cancel": "İptal",
    "market.price": "Fiyat",
    "market.seller": "Satıcı",
    "market.quantity": "Miktar",
    "market.total": "Toplam",
    "market.category.all": "Tümü",
    "market.category.weapon": "Silah",
    "market.category.shoes": "Ayakkabı",
    "market.category.gloves": "Eldiven",
    "market.category.pants": "Pantolon",
    "market.category.top": "Üst",
    "market.category.cloak": "Pelerin",
    "market.category.helmet": "Kask",
    "market.category.accessory": "Aksesuar",
    "market.category.title": "Unvan",
    "market.category.skill": "Beceri",
    "market.listModal.title": "NFT Listele",
    "market.listModal.priceLabel": "Fiyat (VERY)",
    "market.listModal.pricePlaceholder": "Satış fiyatını girin",
    "market.listModal.quantityLabel": "Miktar",
    "market.listModal.submit": "Listele",
    "market.listModal.submitting": "Listeleniyor...",
    "market.sellerModal.title": "Satıcı Seç",
    "market.sellerModal.selectSeller": "Satın alınacak satıcıyı seçin",
    "market.sellerModal.quantity": "Miktar",
    "market.sellerModal.available": "Mevcut",
    "market.sellerModal.buy": "Satın Al",
    "market.history.title": "İşlem Geçmişi",
    "market.history.noHistory": "İşlem geçmişi yok",
    "market.history.bought": "Satın Alındı",
    "market.history.sold": "Satıldı",
    "market.history.listed": "Listelendi",
    "market.history.cancelled": "İptal Edildi",

    // Common
    "common.connect": "Bağlan",
    "common.disconnect": "Bağlantıyı Kes",
    "common.loading": "Yükleniyor...",
    "common.confirm": "Onayla",
    "common.cancel": "İptal",
    "common.save": "Kaydet",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.search": "Ara",
    "common.filter": "Filtre",
    "common.all": "Tümü",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const savedLang = localStorage.getItem("language") as Language;
    if (savedLang && LANGUAGES.some((l) => l.code === savedLang)) {
      setLanguageState(savedLang);
    } else {
      // 브라우저 언어 감지
      const browserLang = navigator.language.split("-")[0];
      const matchedLang = LANGUAGES.find((l) => l.code === browserLang);
      if (matchedLang) {
        setLanguageState(matchedLang.code);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
